version: '3.8'

services:
# Customer Service
  customer-service:
    build: .
    container_name: customer-service
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ../UtsProject:/var/www
      - ../UtsProject/storage/logs:/var/www/storage/logs
    networks:
      - microservices-network
    depends_on:
      - customer-db


  customer-db:
      image: mysql:8.0
      container_name: customer_db
      restart: unless-stopped
      environment:
        MYSQL_DATABASE: customer
        MYSQL_ROOT_PASSWORD: customerroot
        MYSQL_PASSWORD: customerpass
        MYSQL_USER: customeruser
      volumes:
        - customerdbdata:/var/lib/mysql
      ports:
        - "3301:3306"
      networks:
        - microservices-network
      healthcheck:
        test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
        interval: 30s
        timeout: 10s
        retries: 5

  nginx-customer:
      image: nginx:1.19-alpine
      container_name: nginx-customer
      restart: unless-stopped
      ports:
        - "8000:80"
      volumes:
        - ../UtsProject:/var/www
        - ./nginx/customer.conf:/etc/nginx/conf.d/default.conf
      networks:
        - microservices-network
      depends_on:
        - customer-service

networks:
  microservices-network:
     external: true

volumes:
  customerdbdata: